name        : clutter-gst
version     : 3.0.14
release     : 6
source     :
    - http://ftp.gnome.org/pub/gnome/sources/clutter-gst/3.0/clutter-gst-3.0.14.tar.xz : f7c8a7dc479759cad5ff7483cb5a1abbe3efd0b4f83ed0e443dc602430a82de2
license     :
    - LGPL-2.0
summary     : Clutter GStreamer API
builddeps   :
    - pkgconfig(clutter-1.0)
    - pkgconfig(gstreamer-1.0)
    - pkgconfig(gstreamer-plugins-base-1.0)
    - pkgconfig(gstreamer-base-1.0)
    - pkgconfig(gstreamer-pbutils-1.0)
    - pkgconfig(gstreamer-video-1.0)
    - pkgconfig(gstreamer-audio-1.0)
    - pkgconfig(gstreamer-tag-1.0)
    - pkgconfig(cogl-2.0-experimental)
description : |
    Clutter GStreamer API
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
