name       : clutter-gst
version    : 3.0.26
release    : 12
source     :
    - https://download.gnome.org/sources/clutter-gst/3.0/clutter-gst-3.0.26.tar.xz : d8618a6d9accec0f2a8574c5e1220051f8505fb82b20336c26bdbd482aa6cb3a
license    : LGPL-2.0-only
component  : desktop.gnome.core
summary    : Clutter GStreamer API
description: |
    Clutter GStreamer API
builddeps  :
    - pkgconfig(clutter-1.0)
    - pkgconfig(cogl-2.0-experimental)
    - pkgconfig(gstreamer-1.0)
    - pkgconfig(gstreamer-audio-1.0)
    - pkgconfig(gstreamer-base-1.0)
    - pkgconfig(gstreamer-pbutils-1.0)
    - pkgconfig(gstreamer-plugins-base-1.0)
    - pkgconfig(gstreamer-tag-1.0)
    - pkgconfig(gstreamer-video-1.0)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
