name       : clutter-gst
version    : 3.0.18
release    : 9
source     :
    - http://ftp.gnome.org/pub/gnome/sources/clutter-gst/3.0/clutter-gst-3.0.18.tar.xz : 0aec0d0c6020cd19a5bb0dab1165a92748f81a9a3acdfabb0f966d5f53bc8093
license    :
    - LGPL-2.0
summary    : Clutter GStreamer API
builddeps  :
    - pkgconfig(clutter-1.0)
    - pkgconfig(gstreamer-1.0)
    - pkgconfig(gstreamer-plugins-base-1.0)
    - pkgconfig(gstreamer-base-1.0)
    - pkgconfig(gstreamer-pbutils-1.0)
    - pkgconfig(gstreamer-video-1.0)
    - pkgconfig(gstreamer-audio-1.0)
    - pkgconfig(gstreamer-tag-1.0)
    - pkgconfig(cogl-2.0-experimental)
description: |
    Clutter GStreamer API
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
