name       : clutter-gst
version    : 3.0.24
release    : 10
source     :
    - http://ftp.acc.umu.se/pub/gnome/sources/clutter-gst/3.0/clutter-gst-3.0.24.tar.xz : e9f1c87d8f4c47062e952fb8008704f8942cf2d6f290688f3f7d13e83578cc6c
license    : LGPL-2.0
component  : desktop.gnome.core
summary    : Clutter GStreamer API
description: |
    Clutter GStreamer API
builddeps  :
    - pkgconfig(clutter-1.0)
    - pkgconfig(cogl-2.0-experimental)
    - pkgconfig(gstreamer-1.0)
    - pkgconfig(gstreamer-audio-1.0)
    - pkgconfig(gstreamer-base-1.0)
    - pkgconfig(gstreamer-pbutils-1.0)
    - pkgconfig(gstreamer-plugins-base-1.0)
    - pkgconfig(gstreamer-tag-1.0)
    - pkgconfig(gstreamer-video-1.0)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
